package com.example.astrospace;

import java.io.Serializable;

/**
 * This contains a planet's, star's, satellites information including their
 * image path, category for filtering (planets, moons, starts, etc...) and other
 * useful displayable information such as name of the object, greek/latin name,
 * description, distance from earth, age, mass, gallery paths.
 */
public class TelemetryDetails implements Serializable {
    public final int imageSource;
    public final String category;
    public final String name;
    public final String latinName;
    public final String description;
    public final double distanceFromEarth;
    public final double age;
    public final double mass;
    public final int[] galleryPaths;

    public TelemetryDetails(int imageSource, String category, String name, String latinName,
            String description, double distanceFromEarth, double age, double mass, int[] galleryPaths) {
        this.imageSource = imageSource;
        this.category = category;
        this.name = name;
        this.latinName = latinName;
        this.description = description;
        this.distanceFromEarth = distanceFromEarth;
        this.age = age;
        this.mass = mass;
        this.galleryPaths = galleryPaths;
    }

    static TelemetryDetails[] spaceObjects = {
        // Planets
        new TelemetryDetails(R.drawable.mercury, "Planets", "Mercury", "Hermes", "The smallest and innermost planet in the Solar System. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the planets in the Solar System. It is named after the Roman deity Mercury, the messenger to the gods.", 2439.7, 4.54, 3.3011e23, new int[] {R.drawable.mercury_1, R.drawable.mercury_2, R.drawable.mercury_3}),
        new TelemetryDetails(R.drawable.venus, "Planets", "Venus", "Aphrodite", "Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth's night sky after the Moon, Venus can cast shadows and can be, on rare occasion, visible to the naked eye in broad daylight.", 0.72, 4.5, 0.815, new int[] {R.drawable.venus_1, R.drawable.venus_2, R.drawable.venus_3}),
        new TelemetryDetails(R.drawable.earth, "Planets", "Earth", "Terra", "The third planet from the Sun and the only astronomical object known to harbor life. About 29.2% of Earth's surface is land consisting of continents and islands. The remaining 70.8% is covered with water, mostly by oceans but also by lakes, rivers and other fresh water, which together constitute the hydrosphere.", 0, 4.54, 5.97237e24, new int[] {R.drawable.earth_1, R.drawable.earth_2, R.drawable.earth_3}),
        new TelemetryDetails(R.drawable.mars, "Planets", "Mars", "Ares", "The fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In English, Mars carries a name of the Roman god of war, and is often referred to as the \"Red Planet\" because the reddish iron oxide prevalent on its surface gives it a reddish appearance that is distinctive among the astronomical bodies visible to the naked eye.", 227.9, 4.54, 6.4171e23, new int[] {R.drawable.mars_1, R.drawable.mars_2, R.drawable.mars_3}),
        new TelemetryDetails(R.drawable.jupiter, "Planets", "Jupiter", "Zeus", "The fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter is one of the brightest objects visible to the naked eye in the night sky, and has been known to ancient civilizations since before recorded history.", 778.6, 4.54, 1.8986e27, new int[] {R.drawable.jupiter_1, R.drawable.jupiter_2, R.drawable.jupiter_3}),
        new TelemetryDetails(R.drawable.saturn, "Planets", "Saturn", "Cronus", "The sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius about nine times that of Earth. It has only one-eighth the average density of Earth; however, with its larger volume, Saturn is over 95 times more massive. Saturn is named after the Roman god of agriculture; its astronomical symbol (♄) represents the god's sickle.", 1433.5, 4.54, 5.6834e26, new int[] {R.drawable.saturn_1, R.drawable.saturn_2, R.drawable.saturn_3}),
        new TelemetryDetails(R.drawable.uranus, "Planets", "Uranus", "Ouranos", "The seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus is similar in composition to Neptune, and both have bulk chemical compositions which differ from that of the larger gas giants Jupiter and Saturn. For this reason, scientists often classify Uranus and Neptune as \"ice giants\" to distinguish them from the other gas giants.", 2872.5, 4.54, 8.6810e25, new int[] {R.drawable.uranus_1, R.drawable.uranus_2, R.drawable.uranus_3}),
        new TelemetryDetails(R.drawable.neptune, "Planets", "Neptune", "Poseidon", "The eighth and farthest known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. Neptune is 17 times the mass of Earth, slightly more massive than its near-twin Uranus. Neptune is denser and physically smaller than Uranus because its greater mass causes more gravitational compression of its atmosphere.", 4495.1, 4.54, 1.0243e26, new int[] {R.drawable.neptune_1, R.drawable.neptune_2, R.drawable.neptune_3}),
        // Moons
        new TelemetryDetails(R.drawable.moon, "Moons", "Moon", "Luna", "The Moon is Earth's only permanent natural satellite. It is the fifth-largest natural satellite in the Solar System, and the largest among planetary satellites relative to the size of the planet that it orbits (its primary). The Moon is after Jupiter's satellite Io the second-densest satellite in the Solar System among those whose densities are known.", 0.00257, 4.54, 7.34767309e22, new int[] {R.drawable.moon_1, R.drawable.moon_2, R.drawable.moon_3}),
        new TelemetryDetails(R.drawable.io, "Moons", "Io", "Ia", "The innermost of the four Galilean moons of Jupiter. It is the third-closest large moon to its planet, after Ganymede and Callisto. Io is the most volcanically active body in the Solar System and one of only two bodies in the Solar System confirmed to have active tectonics.", 421.7, 4.54, 8.9319e22, new int[] {R.drawable.io_1, R.drawable.io_2}),
        new TelemetryDetails(R.drawable.europa, "Moons", "Europa", "Eurynome", "The third of the four Galilean moons of Jupiter, and the sixth-closest to Jupiter. It is the smallest of the Galilean moons, and the smallest planetary moon in the Solar System. Europa is the only moon known to have a liquid ocean beneath its surface.", 671.1, 4.54, 4.7998e22, new int[] {R.drawable.europa_1, R.drawable.europa_2}),
        new TelemetryDetails(R.drawable.ganymede, "Moons", "Ganymede", "Europa", "The largest of the four Galilean moons of Jupiter, and the largest moon in the Solar System. It is larger than the planet Mercury, and is the largest satellite in the Solar System relative to the size of its primary. Ganymede is the only moon known to have a magnetic field.", 1070.4, 4.54, 1.4819e23, new int[] {R.drawable.ganymede_1, R.drawable.ganymede_2}),
        new TelemetryDetails(R.drawable.callisto, "Moons", "Callisto", "Kallisto", "The fourth of the four Galilean moons of Jupiter, and the seventh-closest to Jupiter. It is the second-largest of the Galilean moons, and the second-largest planetary moon in the Solar System. Callisto is the only moon known to have an atmosphere.", 1882.7, 4.54, 1.0759e23, new int[] {R.drawable.callisto_1, R.drawable.callisto_2}),
        new TelemetryDetails(R.drawable.titan, "Moons", "Titan", "Hyperion", "The largest moon of Saturn and the second-largest natural satellite in the Solar System, after Jupiter's moon Ganymede. Titan is the only moon known to have a dense atmosphere, and the only object in space, other than Earth, where clear evidence of stable bodies of surface liquid has been found.", 2575.5, 4.54, 1.3452e23, new int[] {R.drawable.titan_1, R.drawable.titan_2}),
        new TelemetryDetails(R.drawable.triton, "Moons", "Triton", "Nereus", "The largest natural satellite of the planet Neptune. It is the eighth-largest moon in the Solar System, and the second-largest among the Solar System's giant moons. Triton is the only large moon in the Solar System with a retrograde orbit.", 3547.7, 4.54, 2.14e22, new int[] {R.drawable.triton_1, R.drawable.triton_2}),
        new TelemetryDetails(R.drawable.pluto, "Moons", "Pluto", "Charon", "Pluto is the largest known dwarf planet in the Solar System, discovered in 1930. It was thought to be the 9th planet of our system for 75 years until the discovery of Eris and other similar objects that led to its demotion from a planet to a dwarf planet in 2006.", 5906.4, 4.54, 1.303e22, new int[] {R.drawable.pluto_1, R.drawable.pluto_2}),
        // Stars
        new TelemetryDetails(R.drawable.sun, "Stars", "Sun", "Helios", "The star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, with internal convective motion that generates a magnetic field via a dynamo process. It is by far the most important source of energy for life on Earth.", 695700, 4.54, 1.9891e30, new int[] {R.drawable.sun_1, R.drawable.sun_2, R.drawable.sun_3}),
        // Asteroids
        new TelemetryDetails(R.drawable.cares, "Asteroids", "Ceres", "Dactyl", "The largest object in the asteroid belt that lies between the orbits of Mars and Jupiter, and the only dwarf planet within that region. It is the only asteroid known to be rounded by its own gravity, and the only known dwarf planet whose surface is primarily made of rock.", 2.767, 4.54, 9.393e20, new int[] {R.drawable.cares_1, R.drawable.cares_2, R.drawable.cares_3}),
        new TelemetryDetails(R.drawable.pallas, "Asteroids", "Pallas", "Athena", "The second-largest asteroid in the Solar System, after Ceres. It is the third-most-massive object in the asteroid belt, after Ceres and Vesta. It is the second-largest known dwarf planet, after Eris.", 2.772, 4.54, 2.06e20, new int[] {R.drawable.pallas_1, R.drawable.pallas_2}),
        new TelemetryDetails(R.drawable.vesta, "Asteroids", "Vesta", "Hestia", "The second-most-massive object in the asteroid belt, after Ceres. It is the fourth-largest known body in the Solar System, after Ceres, Pallas, and Eris. It is the largest known asteroid.", 2.772, 4.54, 2.59e20, new int[] {R.drawable.vesta_1, R.drawable.vesta_2}),
        new TelemetryDetails(R.drawable.eros, "Asteroids", "Eros", "Aphrodite", "The most-massive asteroid in the main asteroid belt, and the second-most-massive asteroid in the Solar System, after Ceres. It is the most-massive known dwarf planet, and the largest known object in the asteroid belt.", 2.772, 4.54, 1.66e20, new int[] {R.drawable.eros_1, R.drawable.eros_2, R.drawable.eros_3}),
        // Satellites & Rovers
        new TelemetryDetails(R.drawable.hubble, "Satellites & Rovers", "HST", "Hubble Space Telescope", "The space telescope that was launched into low Earth orbit in 1990 and remains in operation. It was not the first space telescope, but is one of the largest and most versatile, and is well known as both a vital research tool and a public relations boon for astronomy.", 556.7, 4.54, 1.5e4, new int[] {R.drawable.hubble_1, R.drawable.hubble_2, R.drawable.hubble_3}),
        new TelemetryDetails(R.drawable.iss, "Satellites & Rovers", "IIS", "International Space Station", "A space station, or a habitable artificial satellite, in low Earth orbit. Its first component launched into orbit in 1998, with the first long-term residents arriving in November 2000. It has been inhabited continuously since that date.", 408.1, 4.54, 4.5e4, new int[] {R.drawable.iss_1, R.drawable.iss_2, R.drawable.iss_3}),
        new TelemetryDetails(R.drawable.chandra, "Satellites & Rovers", "CXO", "Chandra X-ray Observatory", "A space observatory launched by NASA in 1999. It was the first X-ray telescope to be launched into orbit, and the first of NASA's Great Observatories program. It is the only X-ray telescope designed to be launched into orbit, and the only one that can be pointed at any part of the sky.", 96.5, 4.54, 1.5e4, new int[] {R.drawable.chandra_1}),
        new TelemetryDetails(R.drawable.spitzer, "Satellites & Rovers", "SST", "Spitzer Space Telescope", "A space telescope launched in 2003. It was the fourth and final NASA Great Observatory, and the last of the four launched in the 1990s. It is the successor to the Infrared Astronomical Satellite, which was launched in 1983.", 39.1, 4.54, 1.5e4, new int[] {R.drawable.spitzer_1, R.drawable.spitzer_2}),
        new TelemetryDetails(R.drawable.juno, "Satellites & Rovers", "Juno", "Juno", "A space probe that was launched by NASA on August 5, 2011. It is the first spacecraft to orbit Jupiter, and the fifth to visit the planet. It is expected to arrive at Jupiter in July 2016.", 53.1, 4.54, 1.5e4, new int[] {R.drawable.juno_1, R.drawable.juno_2, R.drawable.juno_3}),
        new TelemetryDetails(R.drawable.newhorizons, "Satellites & Rovers", "New Horizons", "NH", "A space probe that was launched by NASA on January 19, 2006. It is the first spacecraft to fly by Pluto, and the first to explore the Kuiper belt. It is the fastest spacecraft ever launched, and the first spacecraft to be launched directly from Earth into interstellar space.", 43.1, 4.54, 1.5e4, new int[] {R.drawable.newhorizons_1, R.drawable.newhorizons_2, R.drawable.newhorizons_3}),
        new TelemetryDetails(R.drawable.curiosity, "Satellites & Rovers", "Mars Rover", "Curiosity", "A car-sized rover designed to explore the crater Gale on Mars as part of NASA's Mars Science Laboratory mission. Curiosity was launched from Cape Canaveral on November 26, 2011, at 15:02 UTC and landed on Aeolis Palus inside Gale on Mars on August 6, 2012, 05:17 UTC.", 34.1, 4.54, 1.5e4, new int[] {R.drawable.curiosity_1, R.drawable.curiosity_2, R.drawable.curiosity_3}),
        new TelemetryDetails(R.drawable.opportunity, "Satellites & Rovers", "Mars Rover", "Opportunity", "A car-sized rover designed to explore the crater Meridiani Planum on Mars as part of NASA's Mars Exploration Rover mission. It landed in Meridiani Planum on January 25, 2004, 05:35 UTC, three weeks after its twin, Spirit. It is still active, having completed 45.16 km (28.03 mi) of driving as of June 2015.", 34.1, 4.54, 1.5e4, new int[] {R.drawable.opportunity_1, R.drawable.opportunity_2, R.drawable.opportunity_3}),
        new TelemetryDetails(R.drawable.spirit, "Satellites & Rovers", "Mars Rover", "Spirit", "A car-sized rover designed to explore the crater Gusev on Mars as part of NASA's Mars Exploration Rover mission. It landed in Gusev Crater on January 4, 2004, 04:35 UTC, three weeks after its twin, Opportunity. It is still active, having completed 45.16 km (28.03 mi) of driving as of June 2015.", 34.1, 4.54, 1.5e4, new int[] {R.drawable.spirit_1, R.drawable.spirit_2, R.drawable.spirit_3}),
        new TelemetryDetails(R.drawable.sojourner, "Satellites & Rovers", "Mars Rover", "Sojourner", "A six-wheeled robotic rover that was part of NASA's Mars Pathfinder mission. It was the first rover to successfully land on Mars, and the first to transmit images back to Earth. It was launched on June 4, 1996, and landed on Mars on July 4, 1997.", 34.1, 4.54, 1.5e4, new int[] {R.drawable.sojourner_1, R.drawable.sojourner_2, R.drawable.sojourner_3}),
        new TelemetryDetails(R.drawable.viking_1, "Satellites & Rovers", "Mars Rover", "Viking 1", "A robotic spacecraft that was part of NASA's Viking program. It was launched on August 20, 1975, and landed on Mars on July 20, 1976. It was the first spacecraft to successfully land on Mars, and the first to transmit images back to Earth.", 34.1, 4.54, 1.5e4, new int[] {R.drawable.viking_1_1, R.drawable.viking_1_2}),
        new TelemetryDetails(R.drawable.viking_2, "Satellites & Rovers", "Mars Rover", "Viking 2", "A robotic spacecraft that was part of NASA's Viking program. It was launched on August 20, 1975, and landed on Mars on July 20, 1976. It was the first spacecraft to successfully land on Mars, and the first to transmit images back to Earth.", 34.1, 4.54, 1.5e4, new int[] {R.drawable.viking_2_1}),
        new TelemetryDetails(R.drawable.phoenix, "Satellites & Rovers", "Mars Rover", "Phoenix", "A robotic spacecraft that was part of NASA's Mars Exploration Program. It was launched on August 4, 2007, and landed on Mars on May 25, 2008. It was the first spacecraft to land on Mars in the northern hemisphere, and the first to land in the Martian arctic.", 34.1, 4.54, 1.5e4, new int[] {R.drawable.phoenix_1, R.drawable.phoenix_2}),
    };
}